name:                syncbox
version:             0.1.0.1
github:              "damianfral/syncbox"
license:             BSD3
author:              "damianfral"
maintainer:          "huevofritopamojarpan@gmail.com"
copyright:           "2019 damianfral"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:

  - base
  - blaze-html
  - bytestring
  - conduit
  - conduit-extra
  - directory
  - dir-traverse
  - exceptions
  - filepath
  - formatting
  - fsnotify
  - generic-lens
  - http-types
  - lens
  - mime-types
  - monad-control
  - neat-interpolation
  - optparse-generic
  - process
  - protolude
  - servant
  - servant-blaze
  - servant-server
  - servant-conduit
  - sqlite-simple
  - text
  - uuid
  - wai
  - wai-extra
  - warp
  - zip-stream

library:
  source-dirs: ./src/

executables:

  syncbox:
    main         : Main.hs
    source-dirs  : ./src
    dependencies :
      - syncbox
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
